# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# Check the latest recommended versions at https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.examplemod
archives_base_name=leaderboard-hud

# Dependencies
# Check the latest version compatible with 26.2 at https://modrinth.com/mod/fabric-api/versions
fabric_version=0.152.1+26.2
